version: "3"
services:
  mopidy-nick:
    image: nickll/mopidy:raspbian
    container_name: mopidy-nick
    restart: unless-stopped
    depends_on:
      - snapcast-server
    ports:
      - 6680:6680
      - 6600:6600
    volumes:
      - ./docker/data/settings-nick:/var/lib/mopidy/iris
      - /home/pi/jukebox/mopidy-docker/mopidy-nick.conf:/root/.config/mopidy/mopidy.conf
      - /tmp/audio-output:/tmp
  mopidy-anjana:
    image: nickll/mopidy:raspbian                                                                                           
    container_name: mopidy-anjana
    restart: unless-stopped                                                                                                 
    depends_on:                                                                                                               
      - snapcast-server                                                                                                     
    ports:
      - 6681:6680
      - 6601:6600
    volumes:                                                                                                                  
      - ./docker/data/settings-anjana:/var/lib/mopidy/iris                                                                      
      - /home/pi/jukebox/mopidy-docker/mopidy-anjana.conf:/root/.config/mopidy/mopidy.conf
      - /tmp/audio-output:/tmp
  snapcast-server:
    image: nickll/snapcast-server:raspbian
    container_name: snapcast-server
    restart: unless-stopped
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - /tmp/audio-output:/tmp
      - /home/pi/jukebox/snapcast-server-docker/snapserver.conf:/etc/snapserver.conf 
  snapcast-client:
    image: nickll/snapcast-client:raspbian
    container_name: snapcast-client
    restart: unless-stopped
    depends_on:
      - snapcast-server
    devices:
      - /dev/snd
    environment:
      - HOST=jukebox
    

