version: "3"
services:
  librespot-nick:
    image: nickll/librespot
    container_name: librespot-nick
    restart: unless-stopped
    depends_on:
      - snapcast-server
    environment:
      SPOTIFY_NAME: "Home Bassistant" 
      SPOTIFY_USER: "spotify@le-large.net"
      SPOTIFY_PASSWORD: "^Vn5N7HuUt#p&NNr"
      INIT_VOLUME: "100"
    stdin_open: true
    tty: true
    volumes:
      - /tmp/librespot-nick:/data
  librespot-anjana:
    image: nickll/librespot
    container_name: librespot-anjana
    restart: unless-stopped
    depends_on:
      - snapcast-server
    environment:
      SPOTIFY_NAME: "Snapcast"
      SPOTIFY_USER: "anjanaebner@aol.com"
      SPOTIFY_PASSWORD: "Bahnhofspotify93!"
      INIT_VOLUME: "100"
    stdin_open: true
    tty: true
    volumes:
      - /tmp/librespot-anjana:/data
  snapcast-server:
    image: nickll/snapcast-server:raspbian
    container_name: snapcast-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - /tmp/librespot-nick:/tmp/librespot-nick
      - /tmp/librespot-anjana:/tmp/librespot-anjana
      - /home/pi/jukebox/snapcast-server-docker/snapserver.conf:/etc/snapserver.conf 
      - /home/pi/jukebox/snapcast-server-docker/config:/root/.config/snapserver
  snapcast-client:
    image: nickll/snapcast-client:raspbian
    container_name: snapcast-client
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - snapcast-server
    devices:
      - /dev/snd
    environment:
      - HOST=192.168.0.85
      - ID=b8:27:eb:1a:40:19
